const fujifilmData = [
    { name: "FinePix HS50EXR", cropFactor: 5.6 },
    { name: "FinePix S1", cropFactor: 5.6 },
    { name: "FinePix XP60", cropFactor: 5.6 },
    { name: "FinePix XP70", cropFactor: 5.6 },
    { name: "FinePix XP80", cropFactor: 5.6 },
    { name: "FinePix XP90", cropFactor: 5.6 },
    { name: "FinePix XP120", cropFactor: 5.6 },
    { name: "FinePix XP130", cropFactor: 5.6 },
    { name: "FinePix XP140", cropFactor: 5.6 },
    { name: "GFX 100", cropFactor: 0.79 },
    { name: "GFX 100S", cropFactor: 0.79 },
    { name: "GFX 50R", cropFactor: 0.79 },
    { name: "GFX 50S", cropFactor: 0.79 },
    { name: "GFX 50S II", cropFactor: 0.79 },
    { name: "X-A1", cropFactor: 1.5 },
    { name: "X-A2", cropFactor: 1.5 },
    { name: "X-A3", cropFactor: 1.5 },
    { name: "X-A5", cropFactor: 1.5 },
    { name: "X-A7", cropFactor: 1.5 },
    { name: "X-E1", cropFactor: 1.5 },
    { name: "X-E2", cropFactor: 1.5 },
    { name: "X-E2S", cropFactor: 1.5 },
    { name: "X-E3", cropFactor: 1.5 },
    { name: "X-E4", cropFactor: 1.5 },
    { name: "X-H1", cropFactor: 1.5 },
    { name: "X-M1", cropFactor: 1.5 },
    { name: "X-Pro1", cropFactor: 1.5 },
    { name: "X-Pro2", cropFactor: 1.5 },
    { name: "X-Pro3", cropFactor: 1.5 },
    { name: "X-Q1", cropFactor: 3.9 },
    { name: "X-Q2", cropFactor: 3.9 },
    { name: "X-S10", cropFactor: 1.5 },
    { name: "X-T1", cropFactor: 1.5 },
    { name: "X-T10", cropFactor: 1.5 },
    { name: "X-T100", cropFactor: 1.5 },
    { name: "X-T2", cropFactor: 1.5 },
    { name: "X-T20", cropFactor: 1.5 },
    { name: "X-T3", cropFactor: 1.5 },
    { name: "X-T30", cropFactor: 1.5 },
    { name: "X-T30 II", cropFactor: 1.5 },
    { name: "X-T4", cropFactor: 1.5 },
    { name: "XF10", cropFactor: 1.5 },
    { name: "X100", cropFactor: 1.5 },
    { name: "X100F", cropFactor: 1.5 },
    { name: "X100S", cropFactor: 1.5 },
    { name: "X100T", cropFactor: 1.5 },
    { name: "X100V", cropFactor: 1.5 },
    { name: "X10", cropFactor: 3.9 },
    { name: "X20", cropFactor: 3.9 },
    { name: "X30", cropFactor: 3.9 },
    { name: "FinePix S8600", cropFactor: 5.6 },
    { name: "FinePix S9800", cropFactor: 5.6 },
    { name: "FinePix S9900W", cropFactor: 5.6 },
    { name: "X-A10", cropFactor: 1.5 },
    { name: "X-M2", cropFactor: 1.5 },
    { name: "X-T200", cropFactor: 1.5 },
    { name: "X-T100", cropFactor: 1.5 },
    { name: "X-H2", cropFactor: 1.5 },
    { name: "X-H2S", cropFactor: 1.5 },
    { name: "X-T5", cropFactor: 1.5 },
    { name: "GFX 100 IR", cropFactor: 0.79 },
    { name: "FinePix XP150", cropFactor: 5.6 },
    { name: "FinePix XP170", cropFactor: 5.6 },
    { name: "FinePix XP200", cropFactor: 5.6 },
    { name: "FinePix XP300", cropFactor: 5.6 },
    { name: "FinePix XP400", cropFactor: 5.6 },
    { name: "X30", cropFactor: 3.9 },
    { name: "X-S1", cropFactor: 5.6 },
    { name: "X-E2R", cropFactor: 1.5 },
    { name: "X-A20", cropFactor: 1.5 },
    { name: "X-A7R", cropFactor: 1.5 },
    { name: "X-A5R", cropFactor: 1.5 },
    { name: "X-T1R", cropFactor: 1.5 },
    { name: "X-T4R", cropFactor: 1.5 },
    { name: "X-E2R", cropFactor: 1.5 },
    { name: "X-Pro1R", cropFactor: 1.5 },
    { name: "X-T10R", cropFactor: 1.5 },
    { name: "X-Pro2R", cropFactor: 1.5 },
    { name: "X-Pro3R", cropFactor: 1.5 },
    { name: "GFX 50R II", cropFactor: 0.79 },
    { name: "X-E2sR", cropFactor: 1.5 },
    { name: "X-A10R", cropFactor: 1.5 },
    { name: "X-T3R", cropFactor: 1.5 },
    { name: "X-Pro1T", cropFactor: 1.5 },
    { name: "X-T2R", cropFactor: 1.5 },
    { name: "X-E1R", cropFactor: 1.5 },
    { name: "X-E4R", cropFactor: 1.5 }
];

if (typeof populateBrand !== 'undefined') {
    populateBrand("Fujifilm", fujifilmData);
}
