const panasonicData = [
    { name: "Lumix DMC-TZ10", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ18", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ20", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ25", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ30", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ35", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ40", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ55", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ57", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ60", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ70", cropFactor: 5.6 },
    { name: "Lumix DMC-TZ80", cropFactor: 5.6 },
    { name: "Lumix FZ1000", cropFactor: 2.7 },
    { name: "Lumix FZ1000 II", cropFactor: 2.7 },
    { name: "Lumix FZ200", cropFactor: 5.6 },
    { name: "Lumix FZ2500", cropFactor: 2.7 },
    { name: "Lumix FZ300", cropFactor: 5.6 },
    { name: "Lumix FZ47", cropFactor: 5.6 },
    { name: "Lumix FZ70", cropFactor: 5.6 },
    { name: "Lumix FZ150", cropFactor: 5.6 },
    { name: "Lumix FZ60", cropFactor: 5.6 },
    { name: "Lumix G1", cropFactor: 2.0 },
    { name: "Lumix G10", cropFactor: 2.0 },
    { name: "Lumix G2", cropFactor: 2.0 },
    { name: "Lumix G3", cropFactor: 2.0 },
    { name: "Lumix G5", cropFactor: 2.0 },
    { name: "Lumix G6", cropFactor: 2.0 },
    { name: "Lumix G7", cropFactor: 2.0 },
    { name: "Lumix G9", cropFactor: 2.0 },
    { name: "Lumix G80", cropFactor: 2.0 },
    { name: "Lumix G85", cropFactor: 2.0 },
    { name: "Lumix GF9", cropFactor: 2.0 },
    { name: "Lumix GX1", cropFactor: 2.0 },
    { name: "Lumix GX7", cropFactor: 2.0 },
    { name: "Lumix GX8", cropFactor: 2.0 },
    { name: "Lumix GX9", cropFactor: 2.0 },
    { name: "Lumix GX80", cropFactor: 2.0 },
    { name: "Lumix GX85", cropFactor: 2.0 },
    { name: "Lumix GH1", cropFactor: 2.0 },
    { name: "Lumix GH2", cropFactor: 2.0 },
    { name: "Lumix GH3", cropFactor: 2.0 },
    { name: "Lumix GH4", cropFactor: 2.0 },
    { name: "Lumix GH5", cropFactor: 2.0 },
    { name: "Lumix GH5 II", cropFactor: 2.0 },
    { name: "Lumix GH6", cropFactor: 2.0 },
    { name: "Lumix LX100", cropFactor: 2.0 },
    { name: "Lumix LX100 II", cropFactor: 2.0 },
    { name: "Lumix S1", cropFactor: 1.0 },
    { name: "Lumix S1H", cropFactor: 1.0 },
    { name: "Lumix S1R", cropFactor: 1.0 },
    { name: "Lumix S5", cropFactor: 1.0 },
    { name: "Lumix ZS1", cropFactor: 5.6 },
    { name: "Lumix ZS3", cropFactor: 5.6 },
    { name: "Lumix ZS5", cropFactor: 5.6 },
    { name: "Lumix ZS7", cropFactor: 5.6 },
    { name: "Lumix ZS10", cropFactor: 5.6 },
    { name: "Lumix ZS20", cropFactor: 5.6 },
    { name: "Lumix ZS25", cropFactor: 5.6 },
    { name: "Lumix ZS30", cropFactor: 5.6 },
    { name: "Lumix ZS40", cropFactor: 5.6 },
    { name: "Lumix ZS50", cropFactor: 5.6 },
    { name: "Lumix ZS60", cropFactor: 5.6 },
    { name: "Lumix ZS70", cropFactor: 5.6 },
    { name: "Lumix ZS100", cropFactor: 2.7 },
    { name: "Lumix ZS200", cropFactor: 2.7 },
    { name: "Lumix GF7", cropFactor: 2.0 },
    { name: "Lumix GF8", cropFactor: 2.0 },
    { name: "Lumix GF6", cropFactor: 2.0 },
    { name: "Lumix GF5", cropFactor: 2.0 },
    { name: "Lumix G3X", cropFactor: 2.0 },
    { name: "Lumix G2X", cropFactor: 2.0 },
    { name: "Lumix GM1", cropFactor: 2.0 },
    { name: "Lumix GM5", cropFactor: 2.0 },
    { name: "Lumix GF10", cropFactor: 2.0 },
    { name: "Lumix GF11", cropFactor: 2.0 },
    { name: "Lumix GF12", cropFactor: 2.0 },
    { name: "Lumix GH7", cropFactor: 2.0 },
    { name: "Lumix GH8", cropFactor: 2.0 },
    { name: "Lumix GH9", cropFactor: 2.0 },
    { name: "Lumix GH10", cropFactor: 2.0 },
    { name: "Lumix FZ80", cropFactor: 5.6 },
    { name: "Lumix FZ82", cropFactor: 5.6 },
    { name: "Lumix FZ83", cropFactor: 5.6 },
    { name: "Lumix FZ85", cropFactor: 5.6 }
];

if (typeof populateBrand !== 'undefined') {
    populateBrand("Panasonic", panasonicData);
}
