const pentaxData = [
    { name: "645D", cropFactor: 0.79 },
    { name: "645Z", cropFactor: 0.79 },
    { name: "K-1", cropFactor: 1.0 },
    { name: "K-1 Mark II", cropFactor: 1.0 },
    { name: "K-3", cropFactor: 1.5 },
    { name: "K-3 II", cropFactor: 1.5 },
    { name: "K-3 Mark III", cropFactor: 1.5 },
    { name: "K-5", cropFactor: 1.5 },
    { name: "K-5 II", cropFactor: 1.5 },
    { name: "K-7", cropFactor: 1.5 },
    { name: "K-10D", cropFactor: 1.5 },
    { name: "K-20D", cropFactor: 1.5 },
    { name: "K-30", cropFactor: 1.5 },
    { name: "K-50", cropFactor: 1.5 },
    { name: "K-70", cropFactor: 1.5 },
    { name: "K-2000", cropFactor: 1.5 },
    { name: "K-100D", cropFactor: 1.5 },
    { name: "K-100D Super", cropFactor: 1.5 },
    { name: "K-110D", cropFactor: 1.5 },
    { name: "K-200D", cropFactor: 1.5 },
    { name: "K-m", cropFactor: 1.5 },
    { name: "K-r", cropFactor: 1.5 },
    { name: "K-x", cropFactor: 1.5 },
    { name: "K-P", cropFactor: 1.5 },
    { name: "K-S1", cropFactor: 1.5 },
    { name: "K-S2", cropFactor: 1.5 },
    { name: "Q", cropFactor: 5.6 },
    { name: "Q-S1", cropFactor: 4.6 },
    { name: "Q10", cropFactor: 5.6 },
    { name: "Q7", cropFactor: 4.6 },
    { name: "K-1 II", cropFactor: 1.0 },
    { name: "K-3 III Monochrome", cropFactor: 1.5 },
    { name: "K-5 IIs", cropFactor: 1.5 },
    { name: "K-500", cropFactor: 1.5 },
    { name: "K-70 II", cropFactor: 1.5 },
    { name: "K-50 II", cropFactor: 1.5 },
    { name: "K-500 II", cropFactor: 1.5 },
    { name: "K-7 II", cropFactor: 1.5 },
    { name: "K-x II", cropFactor: 1.5 },
    { name: "K-r II", cropFactor: 1.5 },
    { name: "K-01", cropFactor: 1.5 },
    { name: "K-30 II", cropFactor: 1.5 },
    { name: "K-m II", cropFactor: 1.5 },
    { name: "K-r II", cropFactor: 1.5 },
    { name: "K-x II", cropFactor: 1.5 },
    { name: "K-1000", cropFactor: 1.0 },
    { name: "KX", cropFactor: 1.0 },
    { name: "Spotmatic", cropFactor: 1.0 },
    { name: "ME", cropFactor: 1.0 },
    { name: "MX", cropFactor: 1.0 },
    { name: "P30", cropFactor: 1.0 },
    { name: "P30T", cropFactor: 1.0 },
    { name: "Super Program", cropFactor: 1.0 },
    { name: "PZ-1", cropFactor: 1.0 },
    { name: "PZ-1P", cropFactor: 1.0 },
    { name: "ZX-5N", cropFactor: 1.0 },
    { name: "ZX-5", cropFactor: 1.0 },
    { name: "MZ-3", cropFactor: 1.0 },
    { name: "MZ-5N", cropFactor: 1.0 },
    { name: "MZ-S", cropFactor: 1.0 },
    { name: "645", cropFactor: 0.79 },
    { name: "645N", cropFactor: 0.79 },
    { name: "645NII", cropFactor: 0.79 },
    { name: "67", cropFactor: 0.5 },
    { name: "67II", cropFactor: 0.5 },
    { name: "Auto 110", cropFactor: 2.0 },
    { name: "Auto 110 Super", cropFactor: 2.0 }
];

if (typeof populateBrand !== 'undefined') {
    populateBrand("Pentax", pentaxData);
}
