const pentaxData = [
    { name: "645D", cropFactor: 0.79 },
    { name: "645Z", cropFactor: 0.79 },
    { name: "K-1", cropFactor: 1.0 },
    { name: "K-1 Mark II", cropFactor: 1.0 },
    { name: "K-3", cropFactor: 1.5 },
    { name: "K-3 II", cropFactor: 1.5 },
    { name: "K-3 Mark III", cropFactor: 1.5 },
    { name: "K-5", cropFactor: 1.5 },
    { name: "K-5 II", cropFactor: 1.5 },
    { name: "K-7", cropFactor: 1.5 },
    { name: "K-10D", cropFactor: 1.5 },
    { name: "K-20D", cropFactor: 1.5 },
    { name: "K-30", cropFactor: 1.5 },
    { name: "K-50", cropFactor: 1.5 },
    { name: "K-2000", cropFactor: 1.5 },
    { name: "K-100D", cropFactor: 1.5 },
    { name: "K-100D Super", cropFactor: 1.5 },
    { name: "K-110D", cropFactor: 1.5 },
    { name: "K-200D", cropFactor: 1.5 },
    { name: "K-m", cropFactor: 1.5 },
    { name: "K-r", cropFactor: 1.5 },
    { name: "K-x", cropFactor: 1.5 },
    { name: "K-P", cropFactor: 1.5 },
    { name: "K-S1", cropFactor: 1.5 },
    { name: "K-S2", cropFactor: 1.5 },
    { name: "Q", cropFactor: 5.6 },
    { name: "Q-S1", cropFactor: 4.6 },
    { name: "Q10", cropFactor: 5.6 },
    { name: "Q7", cropFactor: 4.6 },
    { name: "K-1 II", cropFactor: 1.0 },
    { name: "K-3 III Monochrome", cropFactor: 1.5 },
    { name: "K-5 IIs", cropFactor: 1.5 },
    { name: "K-500", cropFactor: 1.5 },
    { name: "K-70", cropFactor: 1.5 },
    { name: "K-01", cropFactor: 1.5 },
    { name: "Q7 Mount Shield", cropFactor: 4.6 },
    { name: "Q8 Mount Shield", cropFactor: 4.6 }
];

if (typeof populateBrand !== 'undefined') {
    populateBrand("Pentax", pentaxData);
}
