const sonyData = [
    { name: "Alpha 1", cropFactor: 1.0 },
    { name: "Alpha 300", cropFactor: 1.5 },
    { name: "Alpha 330", cropFactor: 1.5 },
    { name: "Alpha 350", cropFactor: 1.5 },
    { name: "Alpha 390", cropFactor: 1.5 },
    { name: "Alpha 500", cropFactor: 1.5 },
    { name: "Alpha 550", cropFactor: 1.5 },
    { name: "Alpha 580", cropFactor: 1.5 },
    { name: "Alpha 6100", cropFactor: 1.5 },
    { name: "Alpha 6400", cropFactor: 1.5 },
    { name: "Alpha 6600", cropFactor: 1.5 },
    { name: "Alpha 7", cropFactor: 1.0 },
    { name: "Alpha 7 II", cropFactor: 1.0 },
    { name: "Alpha 7 III", cropFactor: 1.0 },
    { name: "Alpha 7 IV", cropFactor: 1.0 },
    { name: "Alpha 7C", cropFactor: 1.0 },
    { name: "Alpha 7R", cropFactor: 1.0 },
    { name: "Alpha 7R II", cropFactor: 1.0 },
    { name: "Alpha 7R III", cropFactor: 1.0 },
    { name: "Alpha 7R IV", cropFactor: 1.0 },
    { name: "Alpha 7R V", cropFactor: 1.0 },
    { name: "Alpha 7S", cropFactor: 1.0 },
    { name: "Alpha 7S II", cropFactor: 1.0 },
    { name: "Alpha 7S III", cropFactor: 1.0 },
    { name: "Alpha 9", cropFactor: 1.0 },
    { name: "Alpha 9 II", cropFactor: 1.0 },
    { name: "Alpha A100", cropFactor: 1.5 },
    { name: "Alpha A200", cropFactor: 1.5 },
    { name: "Alpha A230", cropFactor: 1.5 },
    { name: "Alpha A290", cropFactor: 1.5 },
    { name: "Alpha A3000", cropFactor: 1.5 },
    { name: "Alpha A35", cropFactor: 1.5 },
    { name: "Alpha A37", cropFactor: 1.5 },
    { name: "Alpha A55", cropFactor: 1.5 },
    { name: "Alpha A57", cropFactor: 1.5 },
    { name: "Alpha A58", cropFactor: 1.5 },
    { name: "Alpha A65", cropFactor: 1.5 },
    { name: "Alpha A68", cropFactor: 1.5 },
    { name: "Alpha A77", cropFactor: 1.5 },
    { name: "Alpha A77 II", cropFactor: 1.5 },
    { name: "Alpha A99", cropFactor: 1.0 },
    { name: "Alpha A99 II", cropFactor: 1.0 },
    { name: "Cyber-shot DSC-H300", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-H400", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX350", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX400V", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX50V", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX60", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX60V", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX80", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-HX90V", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-RX1", cropFactor: 1.0 },
    { name: "Cyber-shot DSC-RX1R", cropFactor: 1.0 },
    { name: "Cyber-shot DSC-RX1R II", cropFactor: 1.0 },
    { name: "Cyber-shot DSC-RX10", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX10 II", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX10 III", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX10 IV", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 II", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 III", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 IV", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 V", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 VI", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-RX100 VII", cropFactor: 2.7 },
    { name: "Cyber-shot DSC-W800", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-W810", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-W830", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-WX220", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-WX350", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-WX500", cropFactor: 5.6 },
    { name: "Alpha 7C II", cropFactor: 1.0 },
    { name: "Alpha 7R IIIA", cropFactor: 1.0 },
    { name: "Alpha 7R IVA", cropFactor: 1.0 },
    { name: "Alpha 1 II", cropFactor: 1.0 },
    { name: "Alpha A33", cropFactor: 1.5 },
    { name: "Alpha A37 II", cropFactor: 1.5 },
    { name: "Alpha A55 II", cropFactor: 1.5 },
    { name: "Alpha A57 II", cropFactor: 1.5 },
    { name: "Alpha A58 II", cropFactor: 1.5 },
    { name: "Alpha A68 II", cropFactor: 1.5 },
    { name: "Alpha A77 III", cropFactor: 1.5 },
    { name: "Cyber-shot DSC-W810 II", cropFactor: 5.6 },
    { name: "Cyber-shot DSC-W830 II", cropFactor: 5.6 }
];

if (typeof populateBrand !== 'undefined') {
    populateBrand("Sony", sonyData);
}
